name: Set up WireGuard
description: Set up WireGuard connection

inputs:
  endpoint:
    description: Endpoint in the HOST:PORT format
    required: true
  endpoint_public_key:
    description: Public key of the endpoint
    required: true
  private_ips:
    description: Comma-separated list of IP addresses
    required: true
  allowed_ips:
    description: Comma-separated list of netmasks
    required: true
  private_key:
    description: Private key
    required: true
  dns_servers:
    description: Comma-separated list of DNS servers
    required: false
  keep_alive:
    description: Useful for NAT traversal
    required: false

runs:
  using: composite
  steps:
    - run: ${GITHUB_ACTION_PATH}/setup-wireguard.sh
      shell: bash
      env:
        ALLOWED_IPS: '${{ inputs.allowed_ips }}'
        ENDPOINT: '${{ inputs.endpoint }}'
        ENDPOINT_PUBLIC_KEY: '${{ inputs.endpoint_public_key }}'
        PRIVATE_IPS: '${{ inputs.private_ips }}'
        PRIVATE_KEY: '${{ inputs.private_key }}'
        DNS_SERVERS: '${{ inputs.dns_servers }}'
        KEEP_LIVE: '${{ inputs.keep_alive }}'

branding:
  icon: star
  color: green
